language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-6.0

smalltalk_edge:
  source: peteruhnak/smalltalkCI
  branch: s3-source

cache:
  directories:
    - $SMALLTALK_CI_BUILD_BASE/pharo-local/package-cache

after_success:
  - wget -O- https://raw.githubusercontent.com/peteruhnak/hapao-coverage/master/hapao-coverage.sh | bash

deploy:
  provider: s3
  access_key_id:
    secure: "U9V6Sc6556Qq318dxoJWMBjUGdLwglWFpmQ5IL9Bd4Bhn8k3tBumxbHHqwjtPE7V6DFHX3wC1UFFF9gDrlXE/4KJUOFK2zqX7SfYtM++AfUouqd5V4GKGD4UN7ZpuhlV87m23TluyjZXjuu57x64NClYVWSfimRvk9BKUrpyFPjc31cQ38JjdZ62XggyEqu0H17qAaokt3nKtmxuMD7t1Y3Mdht9Sk+jvD/71cA4LDznZlxrch88+DWqIkXFY6+B6aJgZjvAmEpAtR1SHDqDqjKS0MTe2AhlfpBCoI/udTYMtAyHUQMxqVpUzTYrfEfQ+ltg3GyO7USQV+1Dc0FMMY8Xz1FMFf1BcOOgiI20kRpKlaPHbPnkKQMTq2EDNLZL+sVw5IPEy5y4Z9qvLWj12L8esUuaXeUrB+HMqCn3Qkr/VjHBWc54oG3nSKPYfUBXWhkUv1LkHL7SVtpHcENxzny1pBK4z8tFMeJ6CMe4uMvk/DGIUoI9s4zN1fokTkpq850DyQpRNmrg5qrMphu6/kZfPJw9EdpS9fPjUMnKZ2r8bvz1l8txb8o7hnMWoic+t2Kan8CVwKGuX068iCDj5hj+4cO6yezjhh0UbrQrZPzsmqOU2exn0LvxfsxuhW+FVH93c7uZWE/+z/9feVcJgdTdn6TmAO+Ax82QYBoM0BQ="
  secret_access_key:
    secure: "4cuTTDvuXeP/TKpILJYPTwlt7IGbkBn+aLVnZx3DIJDLEgGd+4k7FFY616X2AwL1lKpewWNvEnh6Y08D2WnEClg5p7gnI+m00uUAGLVWPiXZkWLAgFPuWDVFd9Zdl5KyyXEjBqyHqPAUqqJw9fkRaqBhMVJ4q8jTybMmdeByyIxfgRYtha5TtVh7kbbdEhuDnF0k0DcY67HSYsCRpws5UFs6IFdLrFGO2FbNn73QKA/oHylMu9FXUaT6neiMEDVbz+oYC7fgJVkPQoVzxsfHPiBNEEWvuNr6ibM1aj8LmZJgxauXlFFCCLITqVTIKZ0yCBn2PEeoyoL3EwG8OryyiVzLN8ESeNMZ8E+E9gF68BDACMefIvMqkayE9W64I8KIju6SUFh7kGZoIVBvIcxAiEZMmznwUMNbBPsQgBNmq/AMTsarYOFWL+33n4466g6AkbxRRME+MaiZtg3gQgVVj8wQP0f09cBlTnNRtSyp2R27JkVyjSRcPLDSrJU7FGmDAVTz3HVDs5vVS3G/en5vCDoknWa7XA+WbIiLV4tGFeNcLiRuKiK1i4oWzEV7hatLpF7M9VfKCYH6qkh6n86UeHguXPsj3P0TwRNL2BZnrpMIPJfG0ITvB7iN0GYwX4Bb8tQ01Jwgt3lKBWEjWwvR21W/8wYAP8oRKilj1M25EVY="
  bucket: 'hapao-coverage.peteruhnak-com'
  region: eu-central-1
  local_dir: coverage-result
  upload-dir: $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER
  skip-cleanup: true
  on:
    branch: master
